language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

branches:
  except:
    - /^draft-.*/

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
    - /^draft-.*/

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update
  - composer install

script: phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls -v
