language: php

php:
  - 7.2
  - 7.1

branches:
  except:
    - /^draft-.*/

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
    - /^draft-.*/

before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls --no-update
  - composer install

script: phpunit --coverage-text

after_script:
  - php vendor/bin/php-coveralls -v
